version: '3.8'

services:
  app:
    image: ilievaana/fastapiapp:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:  

networks:
  app-network:  
    driver: overlay

