name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # БЕШЕ МISSING!

      - name: Build & Push Docker image
        run: |
          docker build -t ilievaana/fastapiapp:latest .
          docker push ilievaana/fastapiapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy application
        run: |
          docker pull ilievaana/fastapiapp:latest
          docker-compose down
          docker-compose up -d
